name: Fury CI

on:
  push:
    branches:
      - main
      - 'releases/**'
      - 'deploy/**'
      - 'test*'
    tags:
      - v*
  pull_request:
    paths-ignore:
      - '**/*.md'
      - 'docs/**'
      - 'LICENSE'
      - '.vscode/**'
      - '.gitignore'
      - '.github/**'
    types: ['opened', 'reopened', 'synchronize']

jobs:
  java:
    name: Java CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        java-version: ["8", "11", "17"]
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK ${{ matrix.java-version }}
        uses: actions/setup-java@v3
        with:
          java-version: ${{ matrix.java-version }}
          distribution: 'temurin'
      - name: Install bazel
        run: ./ci/run_ci.sh install_bazel
      - name: Install python
        run: ./ci/run_ci.sh install_python
      - name: Install pyfury
        run: ./ci/run_ci.sh install_pyfury
      - name: Run CI with Maven
        run: PATH="$HOME/miniconda/bin:$PATH" ./ci/run_ci.sh java${{ matrix.java-version }}
  javascript:
    name: Javascript CI
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x, 20.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Run CI with NodeJS
        run: ./ci/run_ci.sh javascript
  rust:
    name: Rust CI
    runs-on: ubuntu-latest
    timeout-minutes: 45
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@nightly
      - run: ./ci/run_ci.sh rust
  cpp:
    name: C++ CI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Install bazel
        run: ./ci/run_ci.sh install_bazel
      - name: Run C++ CI with Bazel
        run: ./ci/run_ci.sh cpp
  python:
    name: Python CI
    # Fix python 3.6 install issue, see
    # https://github.com/rwth-i6/returnn/commit/38ecab17d781c4b74db6a174c8097187380b4ddc
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        python-version: [3.6, 3.9]
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install bazel
        run: ./ci/run_ci.sh install_bazel
      - name: Run Python CI
        run: ./ci/run_ci.sh python
  Lint:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.8
        uses: actions/setup-python@v2
        with:
          python-version: 3.8
      - name: Check code style
        run: ./ci/run_ci.sh format
